SELECT LOWER(t.NUME_TARA), v.ID_VANZATOR, v.NUME_VANZATOR, m.NR_MAGAZINE,  v.VENIT_TOTAL_ADUS, 
CASE 
	WHEN (m.NR_MAGAZINE/t.PRET_DE_EXPORT) > t.PRET_DE_EXPORT THEN INITCAP('ACEST VANAZATOR NE FACE PROFIT.')
    WHEN (m.NR_MAGAZINE/t.PRET_DE_EXPORT) = t.PRET_DE_EXPORT THEN INITCAP('ar trebui sa consideram si alti factori.')
    ELSE 'Nu este profitabi.'
END AS PROFIT  
FROM TARA t, MAGAZIN m, VANZATOR v
WHERE t.ID_TARA = m.ID_TARA
AND v.ID_VANZATOR = m.ID_VANZATOR 
AND v.VENIT_TOTAL_ADUS >= 1500000
ORDER BY m.NR_MAGAZINE;

SELECT a.ID_ANGAJAT, CONCAT(a.NUME, CONCAT(' ', a.PRENUME)) NUME_COMPLET, a.ID_JOB 
FROM (SELECT AVG(SALARIU_MAX) AS SALARIU_MAX_MEDIU FROM JOB) SMD, ANGAJAT a
WHERE a.SALARIU > SMD.SALARIU_MAX_MEDIU;
